stages:
  - build
  - test
  - deploy

variables:
  GOOGLE_PROJECT_ID: ""
  GOOGLE_APP_ENGINE_SERVICE: ""

before_script:
  - echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > keyfile.json
  - gcloud auth activate-service-account --key-file=keyfile.json
  - gcloud config set project $GOOGLE_PROJECT_ID

build:
  stage: build
  script:
    - docker build -t itreg-backend .
    - docker tag itreg-backend gcr.io/$GOOGLE_PROJECT_ID/itreg-backend:$CI_COMMIT_REF_NAME
    - docker push gcr.io/$GOOGLE_PROJECT_ID/itreg-backend:$CI_COMMIT_REF_NAME

test:
  stage: test
  script:
    - ## test

deploy:
  stage: deploy
  only:
    - master  
  script:
    - gcloud app deploy --version $CI_COMMIT_REF_NAME --quiet --project $GOOGLE_PROJECT_ID
