version: '3'

services:
  backend:
    image: itreg-backend
    build: .
    ports:
      - "3001:3001"

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend